nav:
  首页: /
  文档: /tags/wiki/
  人员: /people
  招新: /recruit

logo:
  enabled: true
  url: /assets/nu.png
  width: 50
  height: 50

social_links:
  -
    icon: github
    link: https://github.com/NetUnion